[tools]
bat = "latest"
carapace = "latest"
"cargo:jj-starship" = "latest"
"github:nushell/nushell" = "latest"
jjui = "latest"
jujutsu = "latest"
neovim = "latest"
ripgrep = "latest"
television = "latest"
tlrc = "latest"
uv = "latest"
zoxide = "latest"

[settings]
color_theme = "catppuccin"
experimental = false
