[tools]
atuin = "latest"
bat = "latest"
carapace = "latest"
"github:nushell/nushell" = "latest"
"github:tldr-pages/tldr" = "latest"
neovim = "latest"
ripgrep = "latest"
zoxide = "latest"

[settings]
color_theme = "catppuccin"
